#!/bin/zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export DOTFILES="$HOME/.dotfiles"

# XDG

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# editor

export EDITOR="nvim"
export VISUAL="nvim"

# zsh

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"	# History filepath
export HISTSIZE=10000			# Maximum events for internal history
export SAVEHIST=10000			# Maximum events in history file

# software

export VIMCONFIG="$XDG_CONFIG_HOME/nvim"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/foobar"

# golang

export GOPATH="$HOME/workspace/go"
export GOBIN="$HOME/workspace/go/bin"
export GOCACHE="$XDG_CACHE_HOME/go-build"

# NPM

export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

# PATH

export PATH="$GOBIN:$PATH"		# GOBIN
export PATH="$NPM_BIN:$PATH"		# NPM
